server:
  port: 90

#  数据库链接地址
project:
  jdbc:
    datasource:
      driver: com.mysql.jdbc.Driver
      url: jdbc:mysql://127.0.0.1:3306/ikreai?useUnicode=true
      username: root
      password: 123456
  permission:
    service-roles:
      test_1:
        roles: ["管理员","普通用户"]
  redis:
    service:
      database: 0
    permit:
      database: 1



spring:
  thymeleaf:
    mode: HTML
    suffix: .html
    prefix: classpath:/templates